source "https://rubygems.org"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.5"
gem "dotenv", "~> 3.1"
gem "sequel", "~> 5.88"
gem "mysql2", "~> 0.5"
gem "rack-cors", "~> 2.0"
gem "rack-protection", "~> 4.1"

gem "graphql", "~> 2.3"        # graphql-ruby