services:
  db:
    image: mysql:8.0
    container_name: users-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: usersdb
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "--password=example"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: users-app
    environment:
      PORT: 8080
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: apppass
      DB_NAME: usersdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
