source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-cross_origin"
gem "activerecord", "~> 7.0"
gem "mysql2", ">= 0.5.0"
gem "rake"
gem "swagger-blocks"
gem "mongo"
gem "json"

gem "rackup", "~> 2.2"
gem "puma", "~> 7.0"
gem 'rswag'
gem 'rswag-ui'
gem "jwt"
gem 'rswag-api'